# Configuration file for Travis CI builds,
# which are automatically run when code is pushed to Github.
# To skip a build, add [ci skip] to the commit message.
# This file has been linted using: http://lint.travis-ci.org/

# Use Node.js, to run Yeoman
language: node_js

# Cache directories between builds, to store dependencies
# which take longer to compile or download.
# https://docs.travis-ci.com/user/caching#Caching-directories-(Bundler%2C-dependencies)
# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
# https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
cache:
  directories:
#   - node_modules
#   - vendor
    - $HOME/.npm 

# Install dependencies
# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step
# Note: Remember to run composer update on local dev to get latest updates to dependencies
install:
  - npm install # child plugin
  - npm install bower -g
  - npm install gulp-cli -g
  - npm install yo -g
  - npm link

# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
before_script:
  - mkdir 'wpdtrt-generated-plugin'
  - cd wpdtrt-generated-plugin

# Run the build script
script: ./travis-yo.sh

# Notifications of build results
# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: dotherightthing:Wu2ypwc2wIFZVqVqc2jRkbWw

# Deploy code to Github as a 'release'
# This is run after a tagged commit triggers a successful build
# release.zip is generated by gulp dist
# api_key is generated via: travis setup releases
# which requires my GH username and password
# and creates a Personal Access Token at https://github.com/settings/tokens
# named 'automatic releases for dotherightthing/wpdtrt-tourdates' 
# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: J+MsfSieQwAGhCMnNmLvPwUbz3pgWk5g4bKm1ArWTpLlI+n1rzYyjTZHGWnCpyzC9M0doFkZexnVgc0ckHtXG48D/KS2KKovhx3Q7Zd1I/xiqBipmj+qdaVtbGBPFnVT30rkmHOpWSwg6sN0wvdk7fIxprCV+Bd/V6v7fGOxEt/8yU3kqSdvWp9+5yyXISwthVtMtpJH2HVnYGXFS5mdIsRUQEq13kv1OJZftAYKWrCO/8F0ts0DqgTS8vtoAx85cdvoIMY6T8avZXL9jk9LKFTHe49aJu0pPvIPaTEc+NvcUd/82n/VJw92ZGnxyzEy8QyQ6Gx1ehFlp31nTy8Jo3HvUMOwoJJ0PPvvsjI0XIbDa77Q8+Jx7+MU4psqVt4FVFT8rtOxHzL/okxZLKYSRiyn16GeMlpwVOUpuBW6npyHNpj/7J+rRicHwrbOCX0mJugDGQkEL2Kz9d29tHwNc2R+YO/dnPe3SAtBZ4rXsHjmaTg6se1Y0j3kl1Opr7sVeV/6+6qYI5APWaoeSKrIZeOL0Alar6AMSDgS5oKs1PZ4Xf/5HVv8m5XWE+/whrXkzdHlE4GPwSkLn6PodyNmYPpsMzRkqXOWmvUG/oaan96yxqmrkeIW0Wh08a+xcdhGMvv7B7MkLPYAfUzPb6qnlLVjLNy00PJLQaRoSMXl4zs=
  file: 'release.zip'
  # prevent Travis CI from resetting the working directory
  # which deletes all changes made during the build 
  skip_cleanup: true
  on:
    repo: dotherightthing/generator-wp-plugin-boilerplate
    tags: true
    # https://stackoverflow.com/a/27775257/6850747
    all_branches: true
