# Configuration file for Travis CI builds,
# which are automatically run when code is pushed to Github.
# To skip a build, add [ci skip] to the commit message.

# Use Node.js, to run Yeoman
language: node_js

# Cache directories between builds, to store dependencies
# which take longer to compile or download.
# https://docs.travis-ci.com/user/caching#Caching-directories-(Bundler%2C-dependencies)
# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
# https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
cache:
  directories:
#   - node_modules
#   - vendor
    - $HOME/.npm 

# Specify a newer version of Node than the Travis default
# in order to avoid the build error "Use of const in strict mode"
# https://stackoverflow.com/a/44250453/6850747
before_install:
  - nvm install 6.11.2

# Install dependencies
# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step
# Note: Remember to run composer update on local dev to get latest updates to dependencies
install:
  - npm install # child plugin
  - npm install -g yo
  - npm link

# Make shell script executable
# https://github.com/travis-ci/travis-ci/issues/5804
before_script:
  - chmod a+x travis-yo.sh

# Run the build script
script: ./travis-yo.sh

# Notifications of build results
# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: dotherightthing:Wu2ypwc2wIFZVqVqc2jRkbWw
