# Configuration file for Travis CI builds,
# which are automatically run when code is pushed to Github.
# To skip a build, add [ci skip] to the commit message.

# Use PHP, to use Composer, WordPress and PHPUnit
language: php

# PHP versions to test against
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
php:
  - 5.6.30 # MAMP
#  - 5.5 # Sitehost - fails phpunit version requirement

# Public Environment Variables
# https://docs.travis-ci.com/user/environment-variables
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
env:
  - WP_VERSION=latest WP_MULTISITE=0

# Build Matrix
# consisting of specific runtime/env/exclude/include combinations.
# Each 'include' is run as a separate job.
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
# https://github.com/meitar/wordpress-plugin-skeleton/blob/master/.travis.yml
matrix:
  # reduce the delay in the build status being reported
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  fast_finish: true
  include:
    - php: 5.6.30
      env: WP_VERSION=latest WP_MULTISITE=0

# Cache directories between builds, to store dependencies
# which take longer to compile or download.
# https://docs.travis-ci.com/user/caching#Caching-directories-(Bundler%2C-dependencies)
# https://github.com/wp-cli/sample-plugin/blob/master/.travis.yml
# https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
# ~/files - https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
cache:
  directories:
#   - node_modules
#   - vendor
#    - $HOME/.composer/cache/files
    - $HOME/.npm 

before_install:
  # Install a Second Programming Language (Node, to run Gulp tasks)
  # We need to specify a newer version than the Travis default
  # in order to avoid the build error "Use of const in strict mode"
  # https://docs.travis-ci.com/user/customizing-the-build/#Installing-a-Second-Programming-language
  # https://stackoverflow.com/a/44250453/6850747
  - nvm install 8.11.1
  # Disable XDebug which is only required for Code Coverage reports
  # https://johnblackbourn.com/reducing-travis-ci-build-times-for-wordpress-projects/
  - phpenv config-rm xdebug.ini
  # Fix PHPDoc error:
  # "Unable to find the `dot` command of the GraphViz package. Is GraphViz correctly installed and present in your path?"
  - sudo apt-get install graphviz
  # Expect is required to automate user config of the Yeoman plugin generator
  - sudo apt-get install expect

# Install dependencies
# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step
# Note: Remember to run composer update on local dev to get latest updates to dependencies
install:
  # Adding Yarn to Travis CI - https://gist.github.com/acburdine/61f4f91bacf6554fccdaa394fd14ebbd
  - npm install -g yarn
  - yarn install --non-interactive # child plugin
  - yarn global add gulp-cli
  - yarn global add yo
  # Symlink the package to make the generator available via the commandline:
  - yarn link
  # Install Ruby Gems specified in the Gemfile
  - gem install bundler
  - bundle install

# Make shell script executable
# https://github.com/travis-ci/travis-ci/issues/5804
before_script:
  - chmod a+x travis-yo.sh
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export WPUNIT_DB_USER="root"
  - export WPUNIT_DB_PASS=""
  - export WPUNIT_DB_HOST="localhost"

# Run the build script
script:
  - ./travis-yo.sh

# Notifications of build results
# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false
  slack: $SLACK_AUTH

# Deploy code to Github as a 'release'
# This is run after a tagged commit triggers a successful build
# release.zip is generated by gulp dist
# api_key is generated via: travis setup releases
# which requires my GH username and password
# and creates a Personal Access Token at https://github.com/settings/tokens
# named 'automatic releases for dotherightthing/wpdtrt-plugin-boilerplate' 
# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_AUTH
  file: 'wpdtrt-travistest/release.zip'
  # prevent Travis CI from resetting the working directory
  # which deletes all changes made during the build 
  skip_cleanup: true
  on:
    repo: dotherightthing/generator-wpdtrt-plugin-boilerplate
    tags: true
    # https://stackoverflow.com/a/27775257/6850747
    all_branches: true
